project:
  type: website

website:
  title: "BMMB554"
  repo-url: https://github.com/nekrut/bda
  repo-actions: [edit]
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/nekrut/bda
        text: "Edit on GitHub"
  sidebar:
    contents:
      - section: "Lectures"
        contents:
          - href: lectures/lecture1.ipynb
            text: "1. Python basics"
          - href: lectures/lecture2.qmd
            text: "2. Introduction to Bash"
          - href: lectures/lecture3.ipynb
            text: "3. FASTQ and Quality Scores"
          - href: lectures/lecture4.ipynb
            text: "4. Lists and Dictionaries"
          - href: lectures/lecture5.ipynb
            text: "5. File I/O in Python"
          - href: lectures/lecture6.ipynb
            text: "6. Data Manipulation with Pandas"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



