project:
  type: website

website:
  title: "BMMB554"
  repo-url: https://github.com/nekrut/bda
  repo-actions: [edit]
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/nekrut/bda
        text: "Edit on GitHub"
  sidebar:
    contents:
      - section: "Lectures"
        contents:
          - href: lectures/lecture1.qmd
            text: "1. Getting Started with GitHub"
          - href: lectures/lecture2.qmd
            text: "2. Introduction to Bash"
          - href: lectures/lecture3.ipynb
            text: "3. Py1: Data analysis ecosystem - Crunch, load, visualize"
          - href: lectures/lecture4.ipynb
            text: "4. Py2: Simple sequence manipulation"
          - href: lectures/lecture5.ipynb
            text: "5. Py3: Parsing FASTA"
          - href: lectures/lecture6.ipynb
            text: "6. Py4: FASTQ and Quality Scores"
          # - href: lectures/lecture7.ipynb
          #   text: "7. Lists and Dictionaries"
          # - href: lectures/lecture8.ipynb
          #   text: "8. File I/O in Python"
          # - href: lectures/lecture9.ipynb
          #   text: "9. Data Manipulation with Pandas"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-after-body: _commit-info.html



