<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 21: Interval Operations for Genomic Coordinates – BMMB554</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">BMMB554</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/nekrut/bda"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">Edit on GitHub</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../lectures/lecture1.html">Lectures</a></li><li class="breadcrumb-item"><a href="../lectures/lecture21.html">21. Interval Operations for Genomic Coordinates</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Lectures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Getting Started with GitHub</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Introduction to Bash</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Py1: Data analysis ecosystem - Crunch, load, visualize</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Py2: Simple sequence manipulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Py3: Parsing FASTA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Py4: FASTQ and Quality Scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Py5: Data Manipulation with Pandas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Py6: Building graphs with Altair</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Git and GitHub</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. Publishing Your CV with GitHub Pages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11. Building a Website with Claude Code</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12. Responsible Use of Coding Agents</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13. Sequence Alignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">14. Finding Sequence Matches Quickly</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">15. K-mers, Minimizers, and Minimap2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">17. DNA Sequencing Technologies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">19. Variant Calling in Haploid Systems</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture20.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">20. NGS Data Logistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/lecture21.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">21. Interval Operations for Genomic Coordinates</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#the-genome-browser-intervals-everywhere" id="toc-the-genome-browser-intervals-everywhere" class="nav-link" data-scroll-target="#the-genome-browser-intervals-everywhere">1. The Genome Browser: Intervals Everywhere</a>
  <ul class="collapse">
  <li><a href="#what-is-a-track" id="toc-what-is-a-track" class="nav-link" data-scroll-target="#what-is-a-track">1.1 What Is a Track?</a></li>
  <li><a href="#the-key-insight" id="toc-the-key-insight" class="nav-link" data-scroll-target="#the-key-insight">1.2 The Key Insight</a></li>
  </ul></li>
  <li><a href="#what-is-a-genomic-interval" id="toc-what-is-a-genomic-interval" class="nav-link" data-scroll-target="#what-is-a-genomic-interval">2. What Is a Genomic Interval?</a></li>
  <li><a href="#coordinate-systems" id="toc-coordinate-systems" class="nav-link" data-scroll-target="#coordinate-systems">3. Coordinate Systems</a>
  <ul class="collapse">
  <li><a href="#based-half-open" id="toc-based-half-open" class="nav-link" data-scroll-target="#based-half-open">3.1 0-Based, Half-Open</a></li>
  <li><a href="#based-closed" id="toc-based-closed" class="nav-link" data-scroll-target="#based-closed">3.2 1-Based, Closed</a></li>
  <li><a href="#format-to-coordinate-mapping" id="toc-format-to-coordinate-mapping" class="nav-link" data-scroll-target="#format-to-coordinate-mapping">3.3 Format-to-Coordinate Mapping</a></li>
  <li><a href="#converting-between-systems" id="toc-converting-between-systems" class="nav-link" data-scroll-target="#converting-between-systems">3.4 Converting Between Systems</a></li>
  </ul></li>
  <li><a href="#interval-file-formats" id="toc-interval-file-formats" class="nav-link" data-scroll-target="#interval-file-formats">4. Interval File Formats</a>
  <ul class="collapse">
  <li><a href="#bed-format" id="toc-bed-format" class="nav-link" data-scroll-target="#bed-format">4.1 BED Format</a></li>
  <li><a href="#gff3gtf-format" id="toc-gff3gtf-format" class="nav-link" data-scroll-target="#gff3gtf-format">4.2 GFF3/GTF Format</a></li>
  <li><a href="#vcf-positions" id="toc-vcf-positions" class="nav-link" data-scroll-target="#vcf-positions">4.3 VCF Positions</a></li>
  </ul></li>
  <li><a href="#core-interval-operations" id="toc-core-interval-operations" class="nav-link" data-scroll-target="#core-interval-operations">5. Core Interval Operations</a>
  <ul class="collapse">
  <li><a href="#intersect" id="toc-intersect" class="nav-link" data-scroll-target="#intersect">5.1 Intersect</a></li>
  <li><a href="#subtract" id="toc-subtract" class="nav-link" data-scroll-target="#subtract">5.2 Subtract</a></li>
  <li><a href="#merge" id="toc-merge" class="nav-link" data-scroll-target="#merge">5.3 Merge</a></li>
  <li><a href="#complement" id="toc-complement" class="nav-link" data-scroll-target="#complement">5.4 Complement</a></li>
  <li><a href="#closest" id="toc-closest" class="nav-link" data-scroll-target="#closest">5.5 Closest</a></li>
  <li><a href="#coverage" id="toc-coverage" class="nav-link" data-scroll-target="#coverage">5.6 Coverage</a></li>
  </ul></li>
  <li><a href="#bedtools" id="toc-bedtools" class="nav-link" data-scroll-target="#bedtools">6. BEDTools</a>
  <ul class="collapse">
  <li><a href="#history" id="toc-history" class="nav-link" data-scroll-target="#history">6.1 History</a></li>
  <li><a href="#architecture" id="toc-architecture" class="nav-link" data-scroll-target="#architecture">6.2 Architecture</a></li>
  <li><a href="#command-pattern" id="toc-command-pattern" class="nav-link" data-scroll-target="#command-pattern">6.3 Command Pattern</a></li>
  </ul></li>
  <li><a href="#hands-on-variants-in-s.-aureus" id="toc-hands-on-variants-in-s.-aureus" class="nav-link" data-scroll-target="#hands-on-variants-in-s.-aureus">7. Hands-On: Variants in <em>S. aureus</em></a>
  <ul class="collapse">
  <li><a href="#the-story" id="toc-the-story" class="nav-link" data-scroll-target="#the-story">7.1 The Story</a></li>
  <li><a href="#the-variant-calling-workflow" id="toc-the-variant-calling-workflow" class="nav-link" data-scroll-target="#the-variant-calling-workflow">7.2 The Variant-Calling Workflow</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">7.3 Data</a></li>
  <li><a href="#genes-of-interest" id="toc-genes-of-interest" class="nav-link" data-scroll-target="#genes-of-interest">7.4 Genes of Interest</a></li>
  </ul></li>
  <li><a href="#beyond-bedtools" id="toc-beyond-bedtools" class="nav-link" data-scroll-target="#beyond-bedtools">8. Beyond BEDTools</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/nekrut/bda/edit/main/lectures/lecture21.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../lectures/lecture1.html">Lectures</a></li><li class="breadcrumb-item"><a href="../lectures/lecture21.html">21. Interval Operations for Genomic Coordinates</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Lecture 21: Interval Operations for Genomic Coordinates</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this lecture, you will be able to:</p>
<ul>
<li>Distinguish 0-based half-open from 1-based closed coordinate systems</li>
<li>Read and write BED and GFF/GTF format files</li>
<li>Perform core interval operations: intersect, subtract, merge, complement, closest, and coverage</li>
<li>Use BEDTools in Galaxy to manipulate genomic intervals</li>
<li>Apply interval operations to filter and combine genomic annotations</li>
<li>Navigate the UCSC Genome Browser and recognize tracks as interval datasets</li>
</ul>
<hr>
</section>
<section id="the-genome-browser-intervals-everywhere" class="level2">
<h2 class="anchored" data-anchor-id="the-genome-browser-intervals-everywhere">1. The Genome Browser: Intervals Everywhere</h2>
<p>The <a href="https://genome.ucsc.edu">UCSC Genome Browser</a> is the most widely used tool for visualizing genomic data [4]. It displays a region of a reference genome as a horizontal coordinate axis, with datasets stacked vertically as <strong>tracks</strong>. Here we look at the human <em>TP53</em> tumor suppressor gene on chromosome 17:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/lecture21_ucsc_overview.png" class="img-fluid figure-img"></p>
<figcaption>UCSC Genome Browser showing the TP53 locus on human chromosome 17 (hg38). Each horizontal band is a track—a dataset mapped to genomic coordinates.</figcaption>
</figure>
</div>
<p>The horizontal axis spans ~19 kb of chromosome 17. Every colored block, bar, or line in the image represents a <strong>genomic interval</strong>—a feature with a start and end position on the chromosome.</p>
<section id="what-is-a-track" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-track">1.1 What Is a Track?</h3>
<p>A track is a dataset projected onto genomic coordinates. Each feature within a track is an interval. The browser view above contains over a dozen tracks, each representing a different type of genomic annotation:</p>
<ul>
<li><strong>GENCODE / RefSeq gene models</strong> — exons (thick blocks) and introns (thin lines with arrows) defining transcript structure</li>
<li><strong>OMIM Alleles</strong> — positions of disease-associated variants (single-base intervals)</li>
<li><strong>Common dbSNP</strong> — known polymorphisms from dbSNP release 155</li>
<li><strong>GTEx expression</strong> — tissue-specific expression levels (bar chart mapped to gene intervals)</li>
<li><strong>ENCODE cCREs</strong> — candidate cis-regulatory elements (enhancers, promoters, insulators)</li>
<li><strong>H3K27Ac</strong> — histone acetylation peaks marking active regulatory regions</li>
<li><strong>Conservation (PhyloP)</strong> — per-base conservation scores across 100 vertebrates</li>
<li><strong>Multiz alignments</strong> — cross-species sequence alignments (Rhesus, Mouse, Dog, Elephant, Chicken, Zebrafish)</li>
<li><strong>RepeatMasker</strong> — repetitive elements (SINEs, LINEs, DNA transposons)</li>
</ul>
<p>Zooming in reveals the individual interval features more clearly:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/lecture21_ucsc_tracks.png" class="img-fluid figure-img"></p>
<figcaption>Zoomed view of the TP53 locus (~1.8 kb). Individual exons are visible as distinct blocks; introns as connecting lines. Each block is an interval with a precise start and end coordinate.</figcaption>
</figure>
</div>
</section>
<section id="the-key-insight" class="level3">
<h3 class="anchored" data-anchor-id="the-key-insight">1.2 The Key Insight</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Every track in the genome browser is a collection of genomic intervals. Genes, repeats, regulatory elements, variants, aligned reads—all intervals. The browser is visualizing interval arithmetic. This lecture teaches you to perform that arithmetic yourself.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="what-is-a-genomic-interval" class="level2">
<h2 class="anchored" data-anchor-id="what-is-a-genomic-interval">2. What Is a Genomic Interval?</h2>
<p>Every genomic feature—a gene, an exon, a variant, a ChIP-seq peak, an aligned read—can be represented as an <strong>interval</strong>: a contiguous stretch of a chromosome defined by three values:</p>
<pre><code>(chromosome, start, end)</code></pre>
<p>Interval arithmetic lets us ask relational questions about these features: Which variants fall inside genes? Which peaks overlap promoters? What fraction of the genome is covered by repeats? The answers come from a small set of set-theoretic operations on intervals.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In <a href="../lectures/lecture20.html">Lecture 20</a> we produced VCF files containing variant positions, used GTF gene annotations, and mentioned BEDTools as a key toolkit. This lecture formalizes the interval algebra behind those operations.</p>
</div>
</div>
<hr>
</section>
<section id="coordinate-systems" class="level2">
<h2 class="anchored" data-anchor-id="coordinate-systems">3. Coordinate Systems</h2>
<p>Genomics uses two coordinate conventions. Confusing them causes off-by-one errors—the single most common bug in bioinformatics pipelines.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/lecture21_coordinate_systems.svg" class="img-fluid figure-img"></p>
<figcaption>0-based half-open vs 1-based closed coordinate systems</figcaption>
</figure>
</div>
<section id="based-half-open" class="level3">
<h3 class="anchored" data-anchor-id="based-half-open">3.1 0-Based, Half-Open</h3>
<p>Used by <strong>BED</strong> format.</p>
<ul>
<li>The first base of a chromosome is position <strong>0</strong></li>
<li>The interval is <code>[start, end)</code>—start is included, end is excluded</li>
<li>Length = <code>end - start</code></li>
</ul>
<p>Example: the three bases <code>GTA</code> starting at the third position of <code>ACGTACGT</code> are represented as <code>(2, 5)</code>.</p>
</section>
<section id="based-closed" class="level3">
<h3 class="anchored" data-anchor-id="based-closed">3.2 1-Based, Closed</h3>
<p>Used by <strong>GFF/GTF</strong>, <strong>SAM/BAM</strong>, and <strong>VCF</strong> formats.</p>
<ul>
<li>The first base of a chromosome is position <strong>1</strong></li>
<li>The interval is <code>[start, end]</code>—both start and end are included</li>
<li>Length = <code>end - start + 1</code></li>
</ul>
<p>The same three bases <code>GTA</code> are represented as <code>(3, 5)</code>.</p>
</section>
<section id="format-to-coordinate-mapping" class="level3">
<h3 class="anchored" data-anchor-id="format-to-coordinate-mapping">3.3 Format-to-Coordinate Mapping</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Format</th>
<th>System</th>
<th>First base</th>
<th>End included?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://genome.ucsc.edu/FAQ/FAQformat.html#format1">BED</a></td>
<td>0-based, half-open</td>
<td>0</td>
<td>No</td>
</tr>
<tr class="even">
<td><a href="https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md">GFF/GTF</a></td>
<td>1-based, closed</td>
<td>1</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><a href="https://samtools.github.io/hts-specs/SAMv1.pdf">SAM/BAM</a></td>
<td>1-based, closed</td>
<td>1</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><a href="https://samtools.github.io/hts-specs/VCFv4.3.pdf">VCF</a></td>
<td>1-based</td>
<td>1</td>
<td>N/A (single position)</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>BAM is the binary-compressed form of SAM. Internally BAM stores positions as 0-based, but this is a serialization detail—every tool that reads BAM (<code>samtools</code>, <code>pysam</code>, IGV) presents coordinates as 1-based, identical to SAM. You never need to handle this conversion yourself.</p>
</div>
</div>
</section>
<section id="converting-between-systems" class="level3">
<h3 class="anchored" data-anchor-id="converting-between-systems">3.4 Converting Between Systems</h3>
<p>To convert the same feature:</p>
<ul>
<li>BED → GFF: <code>GFF_start = BED_start + 1</code>, <code>GFF_end = BED_end</code></li>
<li>GFF → BED: <code>BED_start = GFF_start - 1</code>, <code>BED_end = GFF_end</code></li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The Off-by-One Trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Mixing coordinate systems silently shifts every interval by one base. Downstream analyses will appear to work but produce subtly wrong results—variants assigned to wrong genes, peaks missing promoters by one base. Always check which system your files use before combining them.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="interval-file-formats" class="level2">
<h2 class="anchored" data-anchor-id="interval-file-formats">4. Interval File Formats</h2>
<section id="bed-format" class="level3">
<h3 class="anchored" data-anchor-id="bed-format">4.1 <a href="https://genome.ucsc.edu/FAQ/FAQformat.html#format1">BED Format</a></h3>
<p>BED (Browser Extensible Data) is the simplest and most widely used interval format. It is tab-delimited and 0-based half-open.</p>
<p><strong>BED3</strong> — the minimal form:</p>
<pre><code>NC_004318.2 322 1056
NC_004318.2 4528    6356
NC_004318.2 9843    12402</code></pre>
<p>Three columns: <code>chrom</code>, <code>chromStart</code>, <code>chromEnd</code>.</p>
<p><strong>BED6</strong> adds name, score, and strand:</p>
<pre><code>NC_004318.2 322 1056    PF3D7_0400100   0   +
NC_004318.2 4528    6356    PF3D7_0400200   0   -
NC_004318.2 9843    12402   PF3D7_0400300   0   +</code></pre>
<p><strong>BED12</strong> extends to 12 columns, adding fields for thick display regions and block (exon) structure—used for multi-exon gene models in genome browsers.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>BED files must be <strong>tab-delimited</strong> (not space-delimited) and should <strong>not</strong> have a header line. Many tools silently produce wrong results if these conventions are violated.</p>
</div>
</div>
</section>
<section id="gff3gtf-format" class="level3">
<h3 class="anchored" data-anchor-id="gff3gtf-format">4.2 <a href="https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md">GFF3</a>/<a href="https://genome.ucsc.edu/FAQ/FAQformat.html#format4">GTF</a> Format</h3>
<p>GFF3 (General Feature Format) and GTF (Gene Transfer Format, essentially GFF version 2) use nine tab-delimited columns and 1-based closed coordinates:</p>
<pre><code>NC_004318.2 RefSeq  gene    323 1056    .   +   .   ID=PF3D7_0400100;Name=RNF5
NC_004318.2 RefSeq  gene    4529    6356    .   -   .   ID=PF3D7_0400200;Name=PF3D7_0400200</code></pre>
<p>Columns: <code>seqid</code>, <code>source</code>, <code>type</code>, <code>start</code>, <code>end</code>, <code>score</code>, <code>strand</code>, <code>phase</code>, <code>attributes</code>.</p>
<p>Notice the same gene <code>PF3D7_0400100</code> has start=322 in BED and start=323 in GFF—a direct consequence of the coordinate system difference.</p>
</section>
<section id="vcf-positions" class="level3">
<h3 class="anchored" data-anchor-id="vcf-positions">4.3 <a href="https://samtools.github.io/hts-specs/VCFv4.3.pdf">VCF</a> Positions</h3>
<p>VCF uses 1-based coordinates for the <code>POS</code> field. Students encountered this in <a href="../lectures/lecture19.html">Lecture 19</a> and <a href="../lectures/lecture20.html">Lecture 20</a>. A VCF record with <code>POS=1024</code> refers to the 1024th base on the chromosome.</p>
<p>To convert a single-nucleotide variant to BED: <code>BED_start = VCF_POS - 1</code>, <code>BED_end = VCF_POS</code>.</p>
<hr>
</section>
</section>
<section id="core-interval-operations" class="level2">
<h2 class="anchored" data-anchor-id="core-interval-operations">5. Core Interval Operations</h2>
<p>Six operations form the foundation of interval arithmetic in genomics. Nearly every analysis question can be decomposed into a sequence of these operations.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/lecture21_interval_operations.svg" class="img-fluid figure-img"></p>
<figcaption>The six core interval operations</figcaption>
</figure>
</div>
<section id="intersect" class="level3">
<h3 class="anchored" data-anchor-id="intersect">5.1 Intersect</h3>
<p><strong>What it does:</strong> finds the overlapping portions between two interval sets A and B.</p>
<p><strong>Biological use case:</strong> “Which of my called variants fall within annotated genes?” We answered this in Lecture 20 using SnpEff—but the underlying operation is an intersection of variant positions with gene intervals.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bedtools</span> intersect <span class="at">-a</span> variants.bed <span class="at">-b</span> genes.bed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Key flags:</p>
<ul>
<li><code>-wa</code> / <code>-wb</code>: report the original A/B entry (not just the overlap)</li>
<li><code>-v</code>: report entries in A with <strong>no</strong> overlap in B (the anti-join)</li>
<li><code>-f 0.50</code>: require at least 50% of A to be overlapped</li>
<li><code>-r</code>: apply the overlap fraction reciprocally to both A and B</li>
</ul>
</section>
<section id="subtract" class="level3">
<h3 class="anchored" data-anchor-id="subtract">5.2 Subtract</h3>
<p><strong>What it does:</strong> removes portions of A that overlap with B.</p>
<p><strong>Biological use case:</strong> “Remove all variants in repetitive or low-complexity regions before downstream analysis.”</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bedtools</span> subtract <span class="at">-a</span> variants.bed <span class="at">-b</span> repeats.bed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="merge" class="level3">
<h3 class="anchored" data-anchor-id="merge">5.3 Merge</h3>
<p><strong>What it does:</strong> collapses overlapping or adjacent intervals within a single set into non-overlapping intervals.</p>
<p><strong>Biological use case:</strong> “Collapse overlapping exon annotations into non-redundant gene bodies.”</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bedtools</span> sort <span class="at">-i</span> exons.bed <span class="kw">|</span> <span class="ex">bedtools</span> merge <span class="at">-i</span> <span class="at">-</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>bedtools merge</code> requires <strong>sorted</strong> input. Always pipe through <code>bedtools sort</code> first.</p>
</div>
</div>
</section>
<section id="complement" class="level3">
<h3 class="anchored" data-anchor-id="complement">5.4 Complement</h3>
<p><strong>What it does:</strong> returns the regions of the genome <strong>not</strong> covered by any interval in the input set.</p>
<p><strong>Biological use case:</strong> “What fraction of chromosome 4 is intergenic (not covered by any gene annotation)?”</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bedtools</span> complement <span class="at">-i</span> genes.bed <span class="at">-g</span> genome.txt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>-g</code> flag requires a <strong>genome file</strong>—a two-column tab-delimited file listing each chromosome and its length:</p>
<pre><code>NC_004318.2 1200490</code></pre>
</section>
<section id="closest" class="level3">
<h3 class="anchored" data-anchor-id="closest">5.5 Closest</h3>
<p><strong>What it does:</strong> for each interval in A, finds the nearest interval in B.</p>
<p><strong>Biological use case:</strong> “For each intergenic variant, what is the nearest gene?”</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bedtools</span> closest <span class="at">-a</span> intergenic_variants.bed <span class="at">-b</span> genes.bed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="coverage" class="level3">
<h3 class="anchored" data-anchor-id="coverage">5.6 Coverage</h3>
<p><strong>What it does:</strong> counts how many intervals in B overlap each interval in A.</p>
<p><strong>Biological use case:</strong> “How many variants fall within each gene? Which genes have the highest variant density?”</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bedtools</span> coverage <span class="at">-a</span> genes.bed <span class="at">-b</span> variants.bed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Output appends columns for: count of overlaps, number of bases covered, interval length, and fraction covered.</p>
<hr>
</section>
</section>
<section id="bedtools" class="level2">
<h2 class="anchored" data-anchor-id="bedtools">6. BEDTools</h2>
<section id="history" class="level3">
<h3 class="anchored" data-anchor-id="history">6.1 History</h3>
<p>BEDTools was created by Aaron Quinlan and Ira Hall in 2010 [1]. It provides over 30 subcommands for interval manipulation and has become the de facto standard for genomic interval arithmetic. The toolkit is available both on the command line and within Galaxy.</p>
</section>
<section id="architecture" class="level3">
<h3 class="anchored" data-anchor-id="architecture">6.2 Architecture</h3>
<p>Early versions of BEDTools used <strong>interval trees</strong>—a balanced binary search tree where each node stores an interval, enabling overlap queries in O(log n + k) time (n = database intervals, k = overlaps found). For ~25,000 genes, finding overlaps requires roughly 15 comparisons instead of 25,000. Modern BEDTools (v2.18+) defaults to a <strong>sweep-line algorithm</strong> (“chromsweep”) for sorted input, which scans both files in coordinate order and achieves even better performance in practice. The interval tree approach is retained as a fallback for unsorted data.</p>
</section>
<section id="command-pattern" class="level3">
<h3 class="anchored" data-anchor-id="command-pattern">6.3 Command Pattern</h3>
<p>Every BEDTools command follows the same pattern:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bedtools</span> <span class="op">&lt;</span>subcommand<span class="op">&gt;</span> <span class="pp">[</span><span class="ss">options</span><span class="pp">]</span> <span class="at">-a</span> <span class="op">&lt;</span>fileA<span class="op">&gt;</span> -b <span class="op">&lt;</span>fileB<span class="op">&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Common subcommands:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Subcommand</th>
<th>Operation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>intersect</code></td>
<td>Intersect two interval sets</td>
</tr>
<tr class="even">
<td><code>subtract</code></td>
<td>Subtract B from A</td>
</tr>
<tr class="odd">
<td><code>merge</code></td>
<td>Merge overlapping intervals</td>
</tr>
<tr class="even">
<td><code>complement</code></td>
<td>Genome regions not in input</td>
</tr>
<tr class="odd">
<td><code>closest</code></td>
<td>Nearest feature in B for each in A</td>
</tr>
<tr class="even">
<td><code>coverage</code></td>
<td>Count overlaps and compute coverage</td>
</tr>
<tr class="odd">
<td><code>sort</code></td>
<td>Sort intervals by position</td>
</tr>
<tr class="even">
<td><code>getfasta</code></td>
<td>Extract FASTA sequences for intervals</td>
</tr>
<tr class="odd">
<td><code>slop</code></td>
<td>Expand intervals by a fixed number of bases</td>
</tr>
<tr class="even">
<td><code>flank</code></td>
<td>Create intervals from the flanks of features</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="hands-on-variants-in-s.-aureus" class="level2">
<h2 class="anchored" data-anchor-id="hands-on-variants-in-s.-aureus">7. Hands-On: Variants in <em>S. aureus</em></h2>
<section id="the-story" class="level3">
<h3 class="anchored" data-anchor-id="the-story">7.1 The Story</h3>
<p>Kaku et al.&nbsp;[5] conducted a nationwide surveillance of methicillin-resistant <em>Staphylococcus aureus</em> (MRSA) bloodstream infections across 51 Japanese hospitals in 2019. They collected 270 MRSA isolates from blood cultures and performed whole-genome sequencing to characterize the molecular epidemiology of these infections. The key finding: SCC<em>mec</em> type IV has replaced SCC<em>mec</em> type II as the dominant MRSA lineage in Japanese bloodstream infections, with ST8-IV (30.7%) and ST1-IV (29.6%) as the most prevalent combinations. The study revealed distinct geographic patterns—ST1-IV dominated in eastern Japan while ST8-IV was more common in the west—and demonstrated that the newer type IV strains show greater susceptibility to clindamycin and minocycline compared to the older type II strains.</p>
<p>We use a subset of these data—already processed through a variant-calling pipeline—to practice interval operations. Our goal: determine whether specific genes of interest carry mutations in these MRSA isolates.</p>
</section>
<section id="the-variant-calling-workflow" class="level3">
<h3 class="anchored" data-anchor-id="the-variant-calling-workflow">7.2 The Variant-Calling Workflow</h3>
<p>The data in the shared history were generated using the <a href="https://iwc.galaxyproject.org/workflow/haploid-variant-calling-wgs-pe-main/">Paired-End Variant Calling in Haploid System</a> workflow from the Intergalactic Workflow Commission (IWC). This standardized Galaxy workflow takes three inputs—paired-end reads, a reference genome, and gene annotations—and produces an annotated variant table.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/lecture21_haploid_vc_workflow.svg" class="img-fluid figure-img"></p>
<figcaption>Paired-End Variant Calling in Haploid System workflow. Yellow = inputs, blue = processing steps, orange = output, green = QC report. Solid lines = data flow, dashed lines = QC metrics.</figcaption>
</figure>
</div>
<p>The pipeline proceeds in four phases:</p>
<ol type="1">
<li><strong>Quality control</strong>: <code>fastp</code> trims adapters and low-quality bases from paired-end reads</li>
<li><strong>Alignment</strong>: <code>BWA-MEM</code> maps trimmed reads to the reference genome, followed by <code>Samtools view</code> (filtering to properly paired reads) and <code>MarkDuplicates</code> (removing PCR duplicates)</li>
<li><strong>Variant calling</strong>: <code>LoFreq Viterbi</code> realigns reads around indels, then <code>LoFreq Call</code> identifies variants in haploid mode</li>
<li><strong>Annotation</strong>: <code>SnpEff</code> annotates variants with functional effects (missense, synonymous, etc.) and <code>SnpSift</code> extracts key fields into a final table</li>
</ol>
<p>A <code>MultiQC</code> report aggregates quality metrics from fastp, mapping, and deduplication steps. The final output is a collapsed table of annotated variants across all samples.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">7.3 Data</h3>
<p>Import the pre-analyzed history into your Galaxy account:</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Setup
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Make sure you are logged in to <a href="https://usegalaxy.org">usegalaxy.org</a></li>
<li>Import the shared history: <a href="https://usegalaxy.org/u/cartman/h/unnamed-history-13" class="uri">https://usegalaxy.org/u/cartman/h/unnamed-history-13</a></li>
<li>Click <strong>Import history</strong> (the “+” icon at the top of the history panel)</li>
</ol>
</div>
</div>
<p>The history contains variant calls (VCF) and gene annotations (GFF) from the MRSA analysis pipeline.</p>
</section>
<section id="genes-of-interest" class="level3">
<h3 class="anchored" data-anchor-id="genes-of-interest">7.4 Genes of Interest</h3>
<p>We focus on five <em>S. aureus</em> NCTC 8325 genes that play roles in virulence, cell wall maintenance, and antibiotic resistance:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Protein accession</th>
<th>Gene</th>
<th>Function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>YP_500520.1</td>
<td>SAOUHSC_02023</td>
<td>Bifunctional autolysin</td>
</tr>
<tr class="even">
<td>YP_499546.1</td>
<td>SAOUHSC_01049</td>
<td>Predicted protein</td>
</tr>
<tr class="odd">
<td>YP_501041.1</td>
<td>SAOUHSC_02545</td>
<td>Predicted protein</td>
</tr>
<tr class="even">
<td>YP_500662.1</td>
<td>SAOUHSC_02165</td>
<td>Predicted protein</td>
</tr>
<tr class="odd">
<td>YP_499519.1</td>
<td>SAOUHSC_01022</td>
<td>Predicted protein</td>
</tr>
</tbody>
</table>
<p>Our question: <strong>Do any of these genes carry genetic variants in the MRSA isolates?</strong> We will answer this using <code>bedtools intersect</code>—overlaying variant positions with gene coordinates.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Hands-On Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>We will work through this analysis together in class using the Galaxy history above and the BEDTools operations from Sections 5 and 6.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="beyond-bedtools" class="level2">
<h2 class="anchored" data-anchor-id="beyond-bedtools">8. Beyond BEDTools</h2>
<p>BEDTools is the most widely used interval toolkit, but alternatives exist for specific workflows:</p>
<ul>
<li><strong><code>bedops</code></strong> [2]—optimized for speed on very large datasets; uses a streaming architecture that avoids loading entire files into memory</li>
<li><strong><code>pybedtools</code></strong> [3]—a Python wrapper around BEDTools that enables scripting interval operations in Python (with optional conversion to pandas DataFrames)</li>
<li><strong><code>GenomicRanges</code></strong>—the R/Bioconductor equivalent; dominant in the R ecosystem for genomic data analysis</li>
<li><strong><code>bioframe</code></strong>—a pure Python library built on pandas; no BEDTools dependency required</li>
</ul>
<p>The choice depends on your analysis environment: BEDTools for command-line pipelines, <code>pybedtools</code> or <code>bioframe</code> for Python scripts, <code>GenomicRanges</code> for R workflows. The underlying operations are identical.</p>
<hr>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Every genomic feature is an <strong>interval</strong> defined by (chromosome, start, end)</li>
<li><strong>Coordinate systems matter</strong>: BED uses 0-based half-open; GFF/GTF and SAM/BAM use 1-based closed; VCF uses 1-based positions. Mixing systems causes off-by-one errors.</li>
<li>Six core operations—<strong>intersect, subtract, merge, complement, closest, coverage</strong>—form the algebra of genomic interval analysis</li>
<li><strong>BEDTools</strong> is the standard toolkit, available on the command line and in Galaxy</li>
<li>Most genomic analysis questions can be decomposed into sequences of interval operations</li>
</ul>
</div>
</div>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li><a href="https://doi.org/10.1093/bioinformatics/btq033">Quinlan, A.R. &amp; Hall, I.M. (2010). BEDTools: a flexible suite of utilities for comparing genomic features. <em>Bioinformatics</em>, 26(6), 841–842.</a></li>
<li><a href="https://doi.org/10.1093/bioinformatics/bts277">Neph, S. et al.&nbsp;(2012). BEDOPS: high-performance genomic feature operations. <em>Bioinformatics</em>, 28(14), 1919–1920.</a></li>
<li><a href="https://doi.org/10.1093/bioinformatics/btr539">Dale, R.K. et al.&nbsp;(2011). pybedtools: a flexible Python library for manipulating genomic datasets and annotations. <em>Bioinformatics</em>, 27(24), 3423–3424.</a></li>
<li><a href="https://doi.org/10.1101/gr.229102">Kent, W.J. et al.&nbsp;(2002). The Human Genome Browser at UCSC. <em>Genome Research</em>, 12(6), 996–1006.</a></li>
<li><a href="https://doi.org/10.1093/jac/dkac154">Kaku, N. et al.&nbsp;(2022). Changing molecular epidemiology and characteristics of MRSA isolated from bloodstream infections: nationwide surveillance in Japan in 2019. <em>Journal of Antimicrobial Chemotherapy</em>, 77(8), 2130–2141.</a></li>
</ol>


</section>

</main> <!-- /main -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  // Find the "Edit this page" link container
  const repoLinks = document.querySelector('.nav-footer-center, .quarto-other-links, .quarto-code-links');

  // Create commit info element
  const commitDiv = document.createElement('div');
  commitDiv.id = 'commit-info';
  commitDiv.style.cssText = 'font-size: 0.7em; color: #888; margin-top: 0.5em; text-align: center;';

  // Fetch latest commit from GitHub API
  fetch('https://api.github.com/repos/nekrut/bda/commits/main')
    .then(response => response.json())
    .then(data => {
      const date = new Date(data.commit.author.date).toLocaleDateString('en-US', {
        year: 'numeric', month: 'short', day: 'numeric'
      });
      const shortSha = data.sha.substring(0, 7);
      commitDiv.innerHTML = `Last updated: <a href="${data.html_url}" style="color: #888;">${shortSha}</a> (${date})`;

      // Try to insert after repo actions or at bottom of sidebar
      const sidebar = document.querySelector('.sidebar-navigation, .sidebar');
      if (sidebar) {
        sidebar.appendChild(commitDiv);
      } else {
        // Fallback: append to body
        const footer = document.querySelector('.nav-footer') || document.body;
        footer.appendChild(commitDiv);
      }
    })
    .catch(err => console.log('Could not fetch commit info'));
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/nekrut\.github\.io\/bda\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/nekrut/bda/edit/main/lectures/lecture21.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>